### ISSUE TITLE
crontime expressions not working

### ISSUE THREAD

**Issue by stanwebber** [buglss/node-red-clone-inject-with-cronti#1]
i like the flexibility & accessibility of having the inject node combined with cron for scheduling. i tried the following crontime expression, but it does nothing:

0-30/5 20 * * *

am i fundamentally misunderstanding how to use this? is this not a full implementation of cron? what am i missing? thanks.

**Comment by buglss** [comment]
@stanwebber thank you for feedback. I working for this problem.

**Comment by buglss** [comment]
I fixed this bug. Crontime expression validation function not was working all crontime expressions for cronti package. Updated the cronti package.
![image](https://user-images.githubusercontent.com/16067517/185798081-bc5fefb9-91d8-46f1-8691-dd6e75ba3af4.png)
