### ISSUE TITLE
Package did not cleanly uninstall on attempted removal from palette using UI interface.

### ISSUE THREAD

**Issue by lindawr** [buglss/node-red-clone-inject-with-cronti#10]
Attempting to remove the plugin resulted in MODULE_NOT_FOUND

The module was used, then references to it were removed, and then I attempted to remove it from the palette.  Removing it from the palette results in this message in the plugin list;

```
@buglss/node-red-crontinject
2.2.1
MODULE_NOT_FOUND
```

The module no longer shows in the palette list on the left, and is not used in any flow.

Attempting to clean up the installed packages list by reenabling the module produces this error message;

- crontinject : Error: Cannot find module 'cronjo'
Require stack:
- /data/node_modules/@buglss/.node-red-crontinject-F4kje6x7/nodes/crontinject.js
- /usr/src/node-red/node_modules/@node-red/registry/lib/loader.js
- /usr/src/node-red/node_modules/@node-red/registry/lib/index.js
- /usr/src/node-red/node_modules/@node-red/runtime/lib/nodes/index.js
- /usr/src/node-red/node_modules/@node-red/runtime/lib/index.js
- /usr/src/node-red/node_modules/node-red/lib/red.js
- /usr/src/node-red/node_modules/node-red/red.js

The package cannot be reinstalled, as it shows as being already installed.

**Comment by buglss** [comment]
@lindawr Thank you. I will investigate this error. I will try to resolve it shortly.

**Comment by buglss** [comment]
@lindawr I'm sorry for the late reply.

I'm guessing it was interrupted during package installation. For this reason, the full installation may not have taken place. You can try installing and uninstalling with npm.

npm installations are registered in the package-lock.json file. The installation and deletion you did through Node-red's GUI may have been interrupted. The package information may have been written to the package-lock.json file even though it is not complete. This is why you may be getting an error when you want to process from Node-red's GUI.

This issue will be closed according to your reply.
